import { BrowserRouter as Router, Routes, Route, Link } from 'react-router-dom';
import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import axios from "axios";
const logo = require('./assets/user.webp');

const Dashboard = (props) => {
    const navigate = useNavigate();
    const [data, setData] = useState({ firstname: localStorage.getItem("firstname"), lastname: localStorage.getItem("lastname"), email: localStorage.getItem("email"), visualisations: [] });

    useEffect(() => {
        if (!localStorage.getItem("token")) {
            navigate("/login");
        }
        loaddata();
    }, []);
    const loaddata = () => {
        axios.get("http://34.131.205.106:3001/mappings?user="+localStorage.getItem("userid"))
        .then((result) => {
            setData({ ...data, visualisations : result.data.data })
        }, (err) =>  { alert(err.response.data.message)})
    }
    const deleteFunc = (e) => {
        axios.get("http://34.131.205.106:3001/deletemapping?id=" + e.target.value)
        .then((result) => {
            alert("Delete successful")
            loaddata();
        }, (err) =>  { alert(err.response.data.message)})
    }
    const deleteuser = (e) => {
        axios.get("http://34.131.205.106:3001/deleteuser?id=" + localStorage.getItem("userid"))
        .then((result) => {
            alert("Delete successful")
            localStorage.clear();
            props.setLoggedIn(false);
            navigate("/login");
        }, (err) =>  { alert(err.response.data.message)})
    }
    return (
        <div className="profile container">
            <section className="h-100 gradient-custom-2">
                <div className="container py-5 h-100">
                    <div className="row d-flex justify-content-center align-items-center h-100">
                        <div className="col col-lg-12 col-xl-12">
                            <div className="card">
                                <div className="rounded-top text-white d-flex flex-row div-1 rel">
                                    <div className="ms-4 mt-5 d-flex flex-column div-2">
                                        <img src={logo}
                                            alt="Generic placeholder image" className="img-fluid img-thumbnail mt-4 mb-2 div-3" />
                                        <Link to="/resource" type="button" className="btn btn-outline-dark div-4">
                                            Create resource
                                        </Link>
                                    </div>
                                    <div className="ms-3 div-5 ">
                                        <h5>{data.firstname} {data.lastname}</h5>
                                        <p>{data.email}</p>
                                        
                                        <button type="button" className="btn btn-outline-dark div-4 align-button" onClick={deleteuser}>
                                            Delete User
                                        </button>
                                    </div>
                                </div>
                                <div className="p-4 text-black div-6">
                                    <div className="d-flex justify-content-end text-center py-1">
                                        <div>
                                            <p className="mb-1 h5">{data.visualisations.length}</p>
                                            <p className="small text-muted mb-0">Open Links</p>
                                        </div>
                                    </div>
                                </div>
                                <div className="card-body p-4 text-black">
                                    <div className="d-flex justify-content-between align-items-center mb-4">
                                        <p className="lead fw-normal mb-0">Recent Generated Links</p>
                                    </div>
                                    <div className="row g-2">
                                        <table className="table">
                                            <thead>
                                                <tr>
                                                    <th scope="col">#</th>
                                                    <th scope="col">Resource</th>
                                                    <th scope="col">URI</th>
                                                    <th scope="col">Layout</th>
                                                    <th scope="col">Description</th>
                                                    <th scope="col">Generated By</th>
                                                    <th scope="col">Action</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {data.visualisations.map((el, index) => (
                                                    <tr key={index}>
                                                        <th scope="row">{index + 1} </th>
                                                        <td>{el.visualisations}</td>
                                                        <td><Link to={`/vresource?id=${el.id}`}>http://localhost:3000/vresource?id={el.id}</Link></td>
                                                        <td>
                                                            {el.layout === 'a' &&
                                                                <div className="progress">
                                                                    <div className="progress-bar" role="progressbar" style={{ width: '50%' }} aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
                                                                </div>
                                                            }
                                                            {el.layout === 'b' &&
                                                                <div className="progress">
                                                                    <div className="progress-bar" role="progressbar" style={{ width: '25%' }} aria-valuenow="15" aria-valuemin="0" aria-valuemax="100"></div>
                                                                    <div className="progress-bar bg-success" role="progressbar" style={{ width: '25%' }} aria-valuenow="30" aria-valuemin="0" aria-valuemax="100"></div>
                                                                    <div className="progress-bar bg-info" role="progressbar" style={{ width: '25%' }} aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"></div>
                                                                    <div className="progress-bar bg-dark" role="progressbar" style={{ width: '25%' }} aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
                                                                </div>
                                                            }
                                                        </td>
                                                        <td>{el.description}</td>
                                                        <td>{el.fullname}</td>
                                                        <td><button type="button" class="btn btn-danger" value={el.id} onClick={deleteFunc}>Delete</button></td>
                                                    </tr>
                                                ))}
                                                {data.visualisations.length === 0 && 
                                                <tr key={0}>
                                                    <td colSpan="6" className="text-center">No Entries Found</td>
                                                </tr>
                                                }
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    )
}

export default Dashboard;

